const data = [
  {
    author: 'Hyväkysymys.fi',
    url: 'https://www.hyvakysymys.fi/kurssi/tunnekeskeinen-parisuhdekurssi/',
    title: 'Tunnekeskeinen parisuhdekurssi',
    description: 'Tämä kurssi antaa välineitä parisuhteen läheisyyden parantamiseen ja ristiriitojen ratkaisuun. Osallistuminen on maksutonta. Kurssin voit tehdä joko yhdessä kumppanisi kanssa tai yksin. Paras hyöty saadaan, jos molemmat olette halukkaita kurssille ja teette sen yhdessä. Kurssi perustuu tunnekeskeiseen pariterapiaan. Kurssi ei kuitenkaan ole terapiaa. Kurssi on toteutettu Väestöliiton ja Suomen Pariterapiayhdistyksen yhteistyönä. Tämä kurssi ei sovellu pareille, joiden ongelmana on väkivalta.',
    done: false,
    style: 'tehtävä',
  },
  {
    author: 'Väestöliitto.fi',
    url: 'https://www.vaestoliitto.fi/parisuhde/tietoa_parisuhteesta/parisuhteen-itseapukursseja/parisuhteen-taidetehtavat/',
    title: 'Parisuhteen taidetehtävät',
    description: 'Kaikki meistä ovat joskus tunteneet taiteen parantavan voiman. Taiteen tekeminen voi auttaa meitä leikin kautta löytämään uusia puolia itsestämme tai kumppanistamme. Kuvataiteen tekemisellä on myös havaittu olevan monia terveydellisiä hyötyjä.',
    done: false,
    style: 'tehtävä',
  },
  {
    author: 'Väestöliitto.fi',
    url: 'https://www.vaestoliitto.fi/parisuhde/tietoa_parisuhteesta/parisuhteen-itseapukursseja/parisuhteen-elokuvatehtavat/',
    title: 'Parisuhteen elokuvatehtävät',
    description: 'Elokuvien katselu on jotain, mitä pari voi tehdä itsekseen ja toimii hyvänä työkaluna parisuhdeongelmien puheeksi ottamiseen. On helpompaa ottaa asioita puheeksi keskustelemalla niistä elokuvan parisuhteen kautta. Tässä vältetään helpommin toisen syyttämistä tai puolustautumista.',
    done: false,
    style: 'tehtävä',
  },
  {
    author: 'Väestöliitto.fi',
    url: 'https://www.vaestoliitto.fi/parisuhde/tietoa_parisuhteesta/parisuhteen-itseapukursseja/parisuhteen-syventaminen/',
    title: 'Parisuhteen syventäminen',
    description: 'Kaikki parisuhteet ovat erilaisia ja eri ihmisille eri asiat ovat tärkeitä. Kaikissa parisuhteissa ei tarvitse lähteä intiimimpään keskusteluun, eikä kaikilla ole siihen halua tai tarvetta. Nämä tehtävät on koottu pareille, yksilöille, joilla on halua lähteä syventämään parisuhteen keskusteluja. Voit käydä järjestyksessä tehtäviä siihen asti, kuin sinusta tuntuu luontevalta tai turvalliselta.',
    done: false,
    style: 'tehtävä',
  },
  {
    author: 'Väestöliitto.fi',
    url: 'https://www.vaestoliitto.fi/parisuhde/tietoa_parisuhteesta/parisuhteen-itseapukursseja/meidan-tarina/',
    title: 'Meidän tarina',
    description: 'Joskus suhteessa on hyvä palata alkuun ja muistella mikä on tuonut juuri teidät kaksi yhteen. On hyvä muistuttaa itseä niistä tunteista joita toinen ihan alussa sinussa herätti. Olette ehkä vasta suhteen alkupuolella tai sitten takananne on pitkä yhteinen historia. Voit aloittaa alusta ja tehdä tehtäviä siihen asti, kun koet luontevalta.',
    done: false,
    style: 'tehtävä',
  },
  {
    author: 'Väestöliitto.fi',
    url: 'https://www.vaestoliitto.fi/parisuhde/tietoa_parisuhteesta/parisuhteen-itseapukursseja/seksuaalisuus/',
    title: 'Seksuaalisuus',
    description: 'Kertokaa toisillenne mitä kaipaatte, mistä pidätte parisuhteessanne. Arvailu ei kannata.',
    done: false,
    style: 'tehtävä',
  },
  {
    author: 'Hyväkysymys.fi',
    url: 'https://www.hyvakysymys.fi/paivystyschatti/paivystava-psykoterapeutti-vastaa-nuorten-aikuisten-parisuhteen-ongelmiin/',
    title: 'Päivystävä psykoterapeutti',
    description: 'Psykoterapeutti vastaa nuorten aikuisten parisuhteen ongelmiin',
    done: false,
    style: 'ammattiauttaja',
  },
  {
    author: 'Väestöliitto.fi',
    url: 'https://www.vaestoliitto.fi/parisuhde/palvelut/neuvontapuhelin/',
    title: 'Neuvontapuhelin',
    description: 'Puhelin on tarkoitettu tavallisille ihmisille ja erityisesti pienten lasten vanhemmille. Yhteyttä voi ottaa, vaikka varsinaista ongelmaa tai kriisiä ei vielä olisikaan. Oikeita tai vääriä kysymyksiä ei ole. Numeroon on mahdollista soittaa nimettömänä. Keskustelu on luottamuksellista ja päivystäjä vaitiolovelvollinen. Päivystäjällä on kuitenkin lastensuojeluilmoitusvelvollisuus, mikäli puhelussa tulee ilmi lapsen terveyden tai hyvinvoinnin vaarantavia asioita.',
    done: false,
    style: 'ammattiauttaja',
  },
  {
    author: 'Väestöliitonterapiapalvelut.fi',
    url: 'https://vaestoliitonterapiapalvelut.fi/terapiat/pariterapia/',
    title: 'Pariterapia',
    description: 'Joskus voi tuntua, että kumppani on liian lähellä. Tai hän, joka on ollut läheinen, tuntuu yhtäkkiä vieraalta. Toisinaan sanat alkavat loppua ja suhde tuntuu olevan umpisolmussa. Silloin voi olla vaikea ymmärtää miksi asiat ovat niin kuin ovat. Joskus tarvitaan vain vähän vahvistusta sille hyvälle mitä suhteessa jo on.',
    done: false,
    style: 'ammattiauttaja',
    price: 'maksullinen', 
  },
  {
    author: 'Positivepsychology.fi',
    url: 'https://positivepsychology.com/couples-therapy-worksheets-activities/',
    title: '21 Couples Therapy Worksheets, Techniques, & Activities',
    description: 'Until we can find that 100% success guaranteed recipe for a perfect relationship, we’ll have to make do with what we do have – building our relationship skills, communicating effectively, engaging in activities that enhance our connection, and using couples therapy to tackle any of the big issues.',
    done: false,
    style: 'tehtävä',
  },
  {
    author: 'Mielenterveystalo.fi',
    url: 'https://www.mielenterveystalo.fi/aikuiset/itsehoito-ja-oppaat/itsehoito/parisuhteen_omahoito/Pages/default.aspx',
    title: 'Parisuhteen omahoito',
    description: 'Parisuhteen omahoito-ohjelma perustuu tutkittuihin menetelmiin ja kokemustietoon siitä, että läheisyys ja luottamus saavat aikaan elämänlaadun ja terveyden paranemista molemmille. Omahoito-ohjelman harjoitukset on kehitetty tukemaan parin vuorovaikutusta, yhdessä tekemistä ja onnellisuutta. Suurin osa parin elämästä on arkea, joten omahoito-ohjelmakin keskittyy arkisten asioiden sujumiseen.',
    done: false,
    style: 'tehtävä',
  },
  {
    author: 'Perspectivesofroy.com',
    url: 'https://perspectivesoftroy.com/couples-therapy-exercises/',
    title: 'Couples therapy excercises',
    description: 'Couples at any stage of their relationship can benefit from counseling and therapy. While most people consider couples counseling as a last resort before a divorce or breakup, the fact is that happy, healthy couples can also learn valuable lessons from these sessions. If you’re trying to get closer to your partner, the techniques below may help you establish better communication and bonding in the future. Here are the top 10 at-home couples therapy exercises.',
    done: false,
    style: 'tehtävä',
  },
  {
    author: 'Thezoreport.com',
    url: 'https://www.thezoereport.com/p/6-popular-couples-therapy-exercises-you-can-try-now-16016334',
    title: "6 popular couple's therapy excercises",
    description: "Ahead, two relationship experts share the common exercises they often give to their clients. Whether you've been in a relationship for three months or 30 years, these techniques will help you and your S.O. get on same page so you can grow closer than ever before.",
    done: false,
    style: 'tehtävä',
  }
]